[project]
name = "un80-actions"
version = "0.1.0"
description = "UN80 Actions Dashboard"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "pandas>=2.3.3",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
